import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import useSession from "../lib/useSession";
import styles from "../styles/Home.module.css";
import Router from "next/router";

import Button from "../components/common/Button";

const Home: NextPage = () => {
  useSession({
    redirectTo: "/feed",
    redirectIfFound: true,
  });

  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-screen font-sans bg-cover bg-landscape -mt-24">
        <div className="container flex items-center justify-center flex-1 h-full mx-auto">
          <div className="w-full max-w-lg">
            <div className="leading-loose">
              <div className="max-w-sm p-10 m-auto bg-white bg-opacity-25 rounded shadow-xl">
                <p className="text-2xl font-light text-center text-black">
                  Get started
                </p>
                <div className="flex w-full mt-4">
                  <Button
                    onClick={() => {
                      Router.push(`/login`);
                    }}
                    fullWidth
                  >
                    Login
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
